### ISSUE TITLE
> mlflow run . -P steps=download

### ISSUE THREAD

**Issue by drob946** [udacity/Project-Build-an-ML-Pipeline-Starter#11]
Running > mlflow run . -P steps=download returns tons of errors regarding pyarrow. Any help would be appreciated.

**Comment by Bjarrell333** [comment]
I am getting this too. My instructor was of no help and told me to contact udacity. Have you figured it out @drob946

**Comment by rayryeng** [comment]
We believe it has to do with the Python version missing in the conda.yml file in the get_data step.

https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter/blob/main/components/get_data/conda.yml

Try adding python=3.10 as a dependency in the dependencies section and try again.

**Comment by islamalsawy** [comment]
Thank you @drob946 and @Bjarrell333 for reporting it. It should be fixed now.
Thank you @rayryeng for your support. I really appreciate it.
